### ISSUE TITLE
Edgar Glitched

### ISSUE THREAD

**Issue by eiryhun** [Tiniifan/Lynx#1]
When trying to view Edgar in the CharaParam menu, the app glitches and does not load all of his information. Here, I had clicked on Choi before hand, and all information from the TP onwards stays the same as Choi's - this is the same regardless of previous character.
![image](https://github.com/user-attachments/assets/cf52d5c5-62a2-45b0-a2f7-946a18fcb4b0)
![image](https://github.com/user-attachments/assets/12de9de5-acb4-4701-be2e-073633f80559)

Additionally, the following error message appears:
![image](https://github.com/user-attachments/assets/855faea4-9da9-4f49-be2c-81a8b30da9c0)

**Comment by Tiniifan** [comment]
Hi. 

The problem comes from that the fact the base stat limit is set to 100 for each stat, but edgar has 108 for the tp, so it's raise an error. Your problem that the next player keeps the same stats and moveset is another problem, when you click on edgar it raises an error if you do continue, the application ignores the problem but it will stop its code at the error. When the application stops at this error, it has already retrieved the following information: 
1. player id
2. the charabase used by the player
3. trait values (position, element, training type, experience curve)   

other information like stats, fighting spirit and moveset cannot be displayed because the application stopped when reading the tp, so it will display the previous values, but the application will enter a conflict mode because you'll see incorrect values when it has the right values but hasn't been able to display them, that's why do continue when an error is raised is dangerous. 

I've talked a lot but I wanted to explain properly the problem, to conclude, don't worry, I've already fixed the problem, the fix isn't available yet as I'm working on a major update.

![image](https://github.com/user-attachments/assets/fa05bde6-04ff-4dbf-be8b-3bbe15f0e449)

![image](https://github.com/user-attachments/assets/ac387643-4c60-4694-a00f-19c5505bc703)
